accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path(
        "profile_change/<int:pk>/",
        views.UserChangeView.as_view(),
        name="profile_change",
    ),
    path("contact/", views.ContactFormView.as_view(), name="contact"),
    path("contact/result/", views.ContactResultView.as_view(), name="contact_result"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("kakomon.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kakomon/urls.py
from django.urls import path

from . import views

app_name = "kakomon"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/",
        views.ExamListView.as_view(),
        name="list_exam",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/",
        views.SubjectListView.as_view(),
        name="list_subject",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/<subject>/",
        views.QuestionListView.as_view(),
        name="list_question",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/<subject>/",
        views.QuestionListView.as_view(),
        name="list_question_speanking",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/test/",
        views.ExamSubjectListView.as_view(),
        name="list_examsubject",
    ),
]

kakomon/models.py
from django.db import models

from .constants import (
    EXAMTYPE,
    GRADE,
    IMG_DESCRIPTION_OR_QUESTION,
    IMG_RIGHT_OR_UNDER,
    NAVIGATION_OR_ENGINEERING,
    SHOMON,
    SUBJECT,
    SUBJECT_CHOICES,
)
from .functions import default_exam_id, get_file_path, get_image_upload_path

"""1.カテゴリーモデル"""


class Category(models.Model):
    name = models.CharField(verbose_name="カテゴリー", max_length=255)

    class Meta:
        verbose_name = "カテゴリー"
        verbose_name_plural = "1.カテゴリー"

    def __str__(self):
        return self.name


"""2.タグモデル"""


class Tag(models.Model):
    name = models.CharField(verbose_name="タグ", max_length=255)

    class Meta:
        verbose_name = "タグ"
        verbose_name_plural = "2.タグ"

    def __str__(self):
        return self.name


"""3.試験モデル"""


class Exam(models.Model):
    exam_id = models.IntegerField(default=default_exam_id)
    date = models.DateField(verbose_name="定期")
    exam_type = models.CharField(
        verbose_name="筆記・口述", choices=EXAMTYPE, max_length=8
    )
    navigation_or_engineering = models.CharField(
        verbose_name="航海・機関", choices=NAVIGATION_OR_ENGINEERING, max_length=11
    )
    grade = models.CharField(verbose_name="級名", choices=GRADE, max_length=6)

    def __str__(self):
        return f"{self.date.year}年 {self.date.month}月 {self.get_exam_type_display()} {self.get_navigation_or_engineering_display()} {self.get_grade_display()}"

    class Meta:
        ordering = ["-date", "-navigation_or_engineering", "grade"]
        verbose_name = "試験"
        verbose_name_plural = "3.試験"


"""4.科目モデル"""


class Subject(models.Model):
    exam = models.ForeignKey(
        Exam, on_delete=models.CASCADE, related_name="subjects", verbose_name="試験"
    )
    name = models.CharField(verbose_name="科目", choices=SUBJECT, max_length=12)
    name_order = models.IntegerField(
        verbose_name="科目順序", choices=[(v, k) for k, v in SUBJECT_CHOICES.items()]
    )
    file_path = models.FileField(
        verbose_name="PDF", upload_to=get_file_path, null=True, blank=True
    )

    def save(self, *args, **kwargs):
        self.name_order = SUBJECT_CHOICES.get(self.name, 0)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.exam.date.year}年 {self.exam.date.month}月 {self.exam.get_exam_type_display()} {self.exam.get_navigation_or_engineering_display()} {self.exam.get_grade_display()} {self.get_name_display()}"

    class Meta:
        ordering = [
            "-exam__date",
            "-exam__navigation_or_engineering",
            "exam__grade",
            "name_order",
        ]
        verbose_name = "科目"
        verbose_name_plural = "4.科目"


"""5.問題モデル"""


class Question(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="科目")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True
    )
    tags = models.ManyToManyField(Tag, blank=True)
    daimon = models.PositiveSmallIntegerField(verbose_name="大問")
    daimon_description = models.TextField(
        verbose_name="大問説明", null=True, blank=True
    )
    shomon = models.IntegerField(
        verbose_name="小問", choices=SHOMON, null=True, blank=True
    )
    shomon_description = models.TextField(
        verbose_name="小問説明", null=True, blank=True
    )
    edamon = models.PositiveSmallIntegerField(
        verbose_name="枝問", null=True, blank=True
    )
    question_image = models.ImageField(
        verbose_name="問題画像", upload_to=get_image_upload_path, null=True, blank=True
    )
    question_image_position_description_or_question = models.CharField(
        verbose_name="問題画像配置1",
        choices=IMG_DESCRIPTION_OR_QUESTION,
        max_length=11,
        default=None,
        null=True,
        blank=True,
    )
    question_image_position_right_or_under = models.CharField(
        verbose_name="問題画像配置2",
        choices=IMG_RIGHT_OR_UNDER,
        max_length=5,
        default=None,
        null=True,
        blank=True,
    )
    question_no_indent = models.BooleanField(
        verbose_name="問題インデントなし", default=False
    )
    question = models.TextField(verbose_name="問題")
    answer_image = models.ImageField(
        verbose_name="解答画像", upload_to=get_image_upload_path, null=True, blank=True
    )
    answer_image_position_right_or_under = models.CharField(
        verbose_name="解答画像配置",
        choices=IMG_RIGHT_OR_UNDER,
        max_length=5,
        default=None,
        null=True,
        blank=True,
    )
    answer_no_indent = models.BooleanField(
        verbose_name="解答インデントなし", default=False
    )
    answer = models.TextField(verbose_name="解答")
    similar_questions = models.ManyToManyField(
        "self",
        through="SimilarQuestion",
        related_name="related_similar_questions",
        symmetrical=False,
        verbose_name="類似問題",
        blank=True,
    )

    def __str__(self):
        if self.edamon:
            return f"{self.subject.exam.date.year}年 {self.subject.exam.date.month}月 {self.subject.exam.get_exam_type_display()} {self.subject.exam.get_navigation_or_engineering_display()} {self.subject.exam.get_grade_display()} {self.subject.get_name_display()}_大問{self.daimon}_小問{self.shomon}_枝問{self.edamon}"
        else:
            return f"{self.subject.exam.date.year}年 {self.subject.exam.date.month}月 {self.subject.exam.get_exam_type_display()} {self.subject.exam.get_navigation_or_engineering_display()} {self.subject.exam.get_grade_display()} {self.subject.get_name_display()}_大問{self.daimon}_小問{self.shomon}"

    class Meta:
        ordering = [
            "-subject__exam__date",
            "-subject__exam__navigation_or_engineering",
            "subject__exam__grade",
            "subject__name_order",
            "daimon",
            "shomon",
            "edamon",
        ]
        verbose_name = "問題"
        verbose_name_plural = "5.問題"


"""類似問題モデル(中間テーブル)"""


class SimilarQuestion(models.Model):
    similarity_id = models.IntegerField(verbose_name="類似性ID", null=True, blank=True)
    similarity_score = models.IntegerField(
        verbose_name="類似度スコア", null=True, blank=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True
    )
    tags = models.ManyToManyField(Tag, verbose_name="タグ", blank=True)
    source_question = models.ForeignKey(
        Question, verbose_name="元問題", related_name="source", on_delete=models.CASCADE
    )
    similar_question = models.ForeignKey(
        Question,
        verbose_name="類似問題",
        related_name="similar",
        on_delete=models.CASCADE,
    )
    similarity_reason = models.TextField(verbose_name="類似理由", null=True, blank=True)

    class Meta:
        unique_together = ("source_question", "similar_question")
        verbose_name = "類似問題"
        verbose_name_plural = "6.類似問題"

    def __str__(self):
        return f"{self.source_question} -> {self.similar_question}"

kakomon/views.py
from django.db.models import F
from django.views.generic import ListView, TemplateView

from .constants import EXAMTYPE, GRADE, NAVIGATION_OR_ENGINEERING, SUBJECT
from .functions import find_key_for_value, get_exam_id
from .models import Exam, Question, Subject

""" Top画面 """


class IndexView(TemplateView):
    template_name = "kakomon/index.html"


""" 定期試験画面 """


class ExamListView(ListView):
    template_name = "kakomon/list_exam.html"
    model = Exam
    context_object_name = "exams"

    def get_form_kwargs(self):
        self.exam_type = find_key_for_value(self.kwargs.get("exam_type"), EXAMTYPE)
        self.navigation_or_engineering = find_key_for_value(
            self.kwargs.get("navigation_or_engineering"), NAVIGATION_OR_ENGINEERING
        )
        self.grade = find_key_for_value(self.kwargs.get("grade"), GRADE)

    def get_queryset(self):
        queryset = super().get_queryset()

        self.get_form_kwargs()

        # フィルタリング
        queryset = queryset.filter(
            exam_type=self.exam_type,
            navigation_or_engineering=self.navigation_or_engineering,
            grade=self.grade,
        )

        # 日付が新しい順で表示
        queryset = queryset.order_by("-date")
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context.update(
            {
                "exam_type": self.kwargs.get("exam_type"),
                "navigation_or_engineering": self.kwargs.get(
                    "navigation_or_engineering"
                ),
                "grade": self.kwargs.get("grade"),
            }
        )
        return context


""" 科目画面 """


class SubjectListView(ListView):
    template_name = "kakomon/list_subject.html"
    model = Subject
    context_object_name = "subjects"

    def get_form_kwargs(self):
        self.exam_type = find_key_for_value(self.kwargs.get("exam_type"), EXAMTYPE)
        self.navigation_or_engineering = find_key_for_value(
            self.kwargs.get("navigation_or_engineering"), NAVIGATION_OR_ENGINEERING
        )
        self.grade = find_key_for_value(self.kwargs.get("grade"), GRADE)
        self.year = str(self.kwargs.get("year")).zfill(4)
        self.month = self.kwargs.get("month")
        self.exam_id = get_exam_id(
            self.exam_type,
            self.navigation_or_engineering,
            self.grade,
            self.year,
            self.month,
        )

    def get_queryset(self):
        queryset = super().get_queryset()

        self.get_form_kwargs()

        # フィルタリング
        queryset = queryset.filter(exam__exam_id=self.exam_id)
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context.update(
            {
                "exam_type": self.kwargs.get("exam_type"),
                "navigation_or_engineering": self.kwargs.get(
                    "navigation_or_engineering"
                ),
                "grade": self.kwargs.get("grade"),
                "year": self.kwargs.get("year"),
                "month": self.kwargs.get("month"),
            }
        )
        return context


""" 試験日・科目画面"""


class ExamSubjectListView(ListView):
    template_name = "kakomon/list_examsubject.html"
    model = Subject
    context_object_name = "examsubjects"

    def get_form_kwargs(self):
        self.exam_type = find_key_for_value(self.kwargs.get("exam_type"), EXAMTYPE)
        self.navigation_or_engineering = find_key_for_value(
            self.kwargs.get("navigation_or_engineering"), NAVIGATION_OR_ENGINEERING
        )
        self.grade = find_key_for_value(self.kwargs.get("grade"), GRADE)

    def get_queryset(self):
        queryset = super().get_queryset()

        self.get_form_kwargs()

        # フィルタリング
        queryset = queryset.filter(
            exam__exam_type=self.exam_type,
            exam__navigation_or_engineering=self.navigation_or_engineering,
            exam__grade=self.grade,
        )

        # 日付が新しい順で表示
        queryset = queryset.order_by("-exam__date")

        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context.update(
            {
                "exam_type": self.kwargs.get("exam_type"),
                "navigation_or_engineering": self.kwargs.get(
                    "navigation_or_engineering"
                ),
                "grade": self.kwargs.get("grade"),
            }
        )
        return context


""" 問題画面 """


class QuestionListView(ListView):
    template_name = "kakomon/list_question.html"
    model = Question
    context_object_name = "questions"

    def get_form_kwargs(self):
        self.exam_type = find_key_for_value(self.kwargs.get("exam_type"), EXAMTYPE)
        self.navigation_or_engineering = find_key_for_value(
            self.kwargs.get("navigation_or_engineering"), NAVIGATION_OR_ENGINEERING
        )
        self.grade = find_key_for_value(self.kwargs.get("grade"), GRADE)
        self.year = str(self.kwargs.get("year")).zfill(4)
        self.month = self.kwargs.get("month")
        self.exam_id = get_exam_id(
            self.exam_type,
            self.navigation_or_engineering,
            self.grade,
            self.year,
            self.month,
        )
        self.subject = find_key_for_value(self.kwargs.get("subject"), SUBJECT)

    def get_queryset(self):
        queryset = super().get_queryset()

        self.get_form_kwargs()

        # フィルタリング
        queryset = queryset.filter(
            subject__exam__exam_id=self.exam_id, subject__name=self.subject
        )
        # カテゴライズ
        queryset = queryset.order_by(
            F("category").asc(nulls_first=True), "daimon", "shomon", "edamon"
        )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "exam_type": self.kwargs.get("exam_type"),
                "navigation_or_engineering": self.kwargs.get(
                    "navigation_or_engineering"
                ),
                "grade": self.kwargs.get("grade"),
                "year": self.kwargs.get("year"),
                "month": self.kwargs.get("month"),
                "subject": self.kwargs.get("subject"),
            }
        )
        return context

kakomon/templates/kakomon/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Google Font Link for Icons -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
        <!-- MathJaxスクリプト -->
        <script type="text/javascript" src="{% static 'js/mathjax_settings.js' %}"></script>
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container py-3">
                <a class="navbar-brand text-white fs-2" href={% url 'kakomon:index' %}>海技士過去問サイト</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse align-items-center" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link text-white" href={% url 'accounts:profile' user.id %}>マイページ</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link text-white" href={% url 'accounts:login' %}>ログイン</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link text-white" href={% url 'accounts:contact' %}>お問合せ</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block exam_nav %}{% endblock %}
        <main>
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="container-fluid">
                {% block base_page %}{% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-dark">
            {% block footer %}{% include "kakomon/base_footer.html" %}{% endblock %}
        </footer>
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

kakomon/templates/kakomon/base_footer.html
{% block sidebar %}
    <p class="m-0 text-center text-white">
        2024 - Copyright &copy; kaigishi_website
    </p>
{% endblock %}

kakomon/templates/kakomon/list_question.html
{% extends 'kakomon/base_kakomon.html' %}

{% block title %}海技士過去問試験問題{% endblock %}

{% block content %}
    <nav class="border-bottom mt-3 mb-4" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href={% url 'kakomon:index' %}>ホーム</a></li>
            {% if exam_type == "筆記" %}
            <li class="breadcrumb-item"><a href={% url 'kakomon:list_examsubject' exam_type navigation_or_engineering grade %}>{{ exam_type }} {{ navigation_or_engineering }} {{ grade }}</a></li>
            {% endif %}
            <li class="breadcrumb-item"><a href={% url 'kakomon:list_subject' exam_type navigation_or_engineering grade year month %}>{{ year }}年 {{ month }}月 {{ subject }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">問題</li>
        </ol>
    </nav>
    <div class="title mb-3">
        <h2>{{ exam_type }}試験  {{ navigation_or_engineering }}  {{ grade }}</h2>
    </div>
    {% if exam_type == "筆記" %}
    <div class="subtitle mb-3">
        <h3>{{ year }}年 {{ month }}月 {{ subject }}</h3>
    </div>
    {% endif %}
    {% if exam_type == "筆記" %}
        {% regroup questions by daimon as daimon_groups %}
        {% for daimon, questions in daimon_groups %}
            {% for question in questions %}
                <!-- 大問 section -->
                {% ifchanged daimon %}
                <div class="d-flex {% if daimon != 1 %}daimon-mt-custom{% else %}mt-4{% endif %}">
                    <p class="daimon"><span class="border p-1 me-2">問題</span>{{ daimon }}</p>
                    <!-- 大問横に問題説明文表示 -->
                    {% if question.daimon_description %}
                    <p>{{ question.daimon_description | safe | linebreaksbr }}</p>
                    {% endif %}
                </div>
                {% endifchanged %}

                <!-- 小問 section -->
                {% if question.shomon %}
                {% ifchanged question.shomon %}
                {% if question.question_image_position_description_or_question == "shomon" %}
                <div class="d-flex">
                    <div class="order-2 align-items-center ms-3">
                        <img src="{{ question.question_image.url }}" alt="Question Image">
                    </div>
                {% endif %}
                {% if question.edamon == 1 %}
                <div class="order-1">
                {% endif %}
                <div class="d-flex mt-3">
                    <p class="shomon">({{ question.get_shomon_display }})</p>
                    <!-- 小問横 問題説明あり 画像あり 右側 -->
                    {% if question.question_image_position_description_or_question == "description" and question.question_image_position_right_or_under == "right" %}
                    <section>
                        <div class="img-right">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image">
                        </div>
                        <p>{{ question.shomon_description | safe | linebreaksbr }}</p>
                    </section>
                    {% elif question.question_image_position_description_or_question == "description" and question.question_image_position_right_or_under == "under" %}
                    <!-- 小問横 問題説明あり 画像あり 下側 -->
                    <section>
                        <p>{{ question.shomon_description | safe | linebreaksbr }}</p>
                        <div class="img-under">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image">
                        </div>
                    </section>
                    {% else %}
                    <!-- 小問横 問題説明あり 画像なし -->
                    <p>{{ question.shomon_description | safe | linebreaksbr }}</p>
                    {% endif %}
                    <section>
                        <!-- 小問 画像あり 右側 -->
                        {% if not question.edamon %}
                        {% if question.question_image_position_description_or_question == "question" and question.question_image_position_right_or_under == "right" %}
                        <div class="img-right">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image"> 
                        </div>
                        {% endif %}
                        <!-- 小問  -->
                        {% if question_no_indent %}
                        <p class="no-indent">{{ question.question | safe | linebreaksbr }}</p>
                        {% else %}
                        <p>{{ question.question | safe | linebreaksbr }}</p>
                        {% endif %}
                        <!-- 小問 画像あり 下側 -->
                        {% if question.question_image_position_description_or_question == "question" and question.question_image_position_right_or_under == "under" %}
                        <div class="img-under">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image">
                        </div>
                        {% endif %}
                        {% endif %}
                    </section>
                </div>
                {% endifchanged %}
                <!-- 小問番号なし（航海・英語で使用） -->
                {% else %}
                <div class="lh-lg">
                    <p>{{ question.question | safe | linebreaksbr }}</p>
                    {% if question.question_image_position_description_or_question == "question" and question.question_image_position_right_or_under == "under" %}
                    <div class="img-under">
                        <div>
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image">
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endif %}

                <!-- 枝問 section -->
                {% if question.edamon %}
                <div class="d-flex">
                    <p class="edamon">（{{ question.edamon }}）</p>
                    <!-- 枝問 画像あり 右側 -->
                    <section>
                        {% if question.question_image_position_description_or_question == "question" and question.question_image_position_right_or_under == "right" %}
                        <div class="img-right">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image"> 
                        </div>
                        {% endif %}
                        <!-- 枝問  -->
                        {% if question.question_no_indent %}
                        <p class="no-indent">{{ question.question | safe | linebreaksbr }}</p>
                        {% else %}
                        <p>{{ question.question | safe | linebreaksbr }}</p>
                        {% endif %}
                        <!-- 枝問 画像あり 下側 -->
                        {% if question.question_image_position_description_or_question == "question" and question.question_image_position_right_or_under == "under" %}
                        <div class="img-under">
                            <img src="{{ question.question_image.url }}" class="img-fluid" alt="Question Image">
                        </div>
                        {% endif %}
                    </section>
                </div>
                {% endif %}
                <!-- 解答 section -->
                <details class="details">
                    <summary class="details__summary">正解を表示する</summary>
                    {% if question.answer_no_indent %}
                        <div class="details__content">
                            <p class="ps-2 no-indent">{{ question.answer | safe | linebreaksbr }}</p>
                            {% if question.answer_image %}
                            <div>
                                <img src="{{ question.answer_image.url }}" class="img-fluid" alt="Answer Image">
                            </div>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="details__content">
                            <p class="ps-2">{{ question.answer | safe | linebreaksbr }}</p>
                            {% if question.answer_image %}
                            <div>
                                <img src="{{ question.answer_image.url }}" class="img-fluid" alt="Answer Image">
                            </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </details>
                {% if question.edamon == 3 %}
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% elif exam_type == "口述" %}
        {% regroup questions by category as categorys %}
        {% for category in categorys %}
            <div class="subtitle mb-3">
                <h3>第{{ forloop.counter }}章  {{ category.grouper }}</h3>
            </div>
            {% regroup category.list by tags.all.0.name as tag_list %}
            {% for tag in tag_list %}
                <div class="subtitle mb-3">
                    <h4>{{ tag.grouper }}</h4>
                </div>
                {% for question in  tag.list %}
                    <p class="no-indent">{{ question.question | safe | linebreaksbr }}</p>
                    <!-- 解答 section -->
                    <details class="details">
                        <summary class="details__summary">正解を表示する</summary>
                        {% if question.answer_no_indent %}
                            <div class="details__content">
                                <p class="ps-2 no-indent">{{ question.answer | safe | linebreaksbr }}</p>
                                {% if question.answer_image %}
                                <div>
                                    <img src="{{ question.answer_image.url }}" class="img-fluid" alt="Answer Image">
                                </div>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="details__content">
                                <p class="ps-2">{{ question.answer | safe | linebreaksbr }}</p>
                                {% if question.answer_image %}
                                <div>
                                    <img src="{{ question.answer_image.url }}" class="img-fluid" alt="Answer Image">
                                </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    </details>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock %}