accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("profile/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path(
        "profile_change/<int:pk>/",
        views.UserChangeView.as_view(),
        name="profile_change",
    ),
    path("contact/", views.ContactFormView.as_view(), name="contact"),
    path("contact/result/", views.ContactResultView.as_view(), name="contact_result"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("kakomon.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kakomon/urls.py
from django.urls import path

from . import views

app_name = "kakomon"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/",
        views.ExamListView.as_view(),
        name="list_exam",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/",
        views.SubjectListView.as_view(),
        name="list_subject",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/<subject>/",
        views.QuestionListView.as_view(),
        name="list_question",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/<int:year>/<int:month>/<subject>/",
        views.QuestionListView.as_view(),
        name="list_question_speanking",
    ),
    path(
        "<exam_type>/<navigation_or_engineering>/<grade>/test/",
        views.ExamSubjectListView.as_view(),
        name="list_examsubject",
    ),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_contribute(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_contribute = True
        user.is_staff = True
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_contribute = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="Eメールアドレス", max_length=255, unique=True
    )
    is_active = models.BooleanField(default=True)  # 一般ユーザー
    is_contribute = models.BooleanField(default=False)  # 問題投稿者
    is_staff = models.BooleanField(default=False)  # Django Adminサイトへのアクセス権
    is_superuser = models.BooleanField(default=False)  # スーパーユーザー

    username = models.CharField(
        verbose_name="ユーザー名", max_length=100, blank=True, null=True
    )
    last_name = models.CharField(
        verbose_name="名字", max_length=100, blank=True, null=True
    )
    first_name = models.CharField(
        verbose_name="名前", max_length=100, blank=True, null=True
    )

    USERNAME_FIELD = "email"

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

accounts/forms.py
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from smtplib import SMTP

from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import EmailField, EmailInput, ModelForm

from .models import CustomUser

"""ログイン"""


class CustomAuthenticationForm(AuthenticationForm):
    username = EmailField(
        label="Eメールアドレス",
        widget=EmailInput(
            attrs={"class": "form-control", "placeholder": "", "required": True}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


"""サインアップ"""


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True
        self.fields["password1"].help_text = ""

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


"""ユーザー情報編集"""


class UserChangeForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "last_name",
            "first_name",
            "email",
        )
        labels = {
            "username": "ユーザー名",
            "last_name": "名 字",
            "first_name": "名 前",
            "email": "メールアドレス",
        }

    def __init__(self, *args, **kwargs):
        # ユーザーの更新前情報をフォームに挿入
        super(UserChangeForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if (
            email
            and CustomUser.objects.filter(email=email)
            .exclude(id=self.instance.id)
            .exists()
        ):
            raise ValidationError(
                "この Eメールアドレス を持った Custom user が既に存在します。"
            )
        return email

    def change_fields(self):
        # 変更されたフィールドを追跡するリスト
        changed_fields = []
        if self.initial.get("username") != self.cleaned_data.get("username"):
            changed_fields.append("ユーザー名")
        if self.initial.get("last_name") != self.cleaned_data.get("last_name"):
            changed_fields.append("名 字")
        if self.initial.get("first_name") != self.cleaned_data.get("first_name"):
            changed_fields.append("名 前")
        if self.initial.get("email") != self.cleaned_data.get("email"):
            changed_fields.append("メールアドレス")
        return changed_fields

    def save(self, commit=True):
        self.instance.username = self.cleaned_data["username"]
        self.instance.first_name = self.cleaned_data["first_name"]
        self.instance.last_name = self.cleaned_data["last_name"]
        self.instance.email = self.cleaned_data["email"]
        if commit:
            self.instance.save()
        return self.instance


class ContactForm(forms.Form):
    name = forms.CharField(
        label="お名前",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "お名前",
            }
        ),
    )

    email = forms.EmailField(
        label="メールアドレス",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "メールアドレス",
            }
        ),
    )

    subject = forms.ChoiceField(
        choices=(
            (1, "1. 問題 訂正"),
            (2, "2. 解答 作成"),
            (3, "3. 新規問題 追加"),
            (4, "4. その他"),
        ),
        required=True,
        widget=forms.widgets.Select,
    )

    message = forms.CharField(
        label="お問合わせ内容",
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "お問合わせ内容（例：問題訂正） \n \n試験日: 2023年7月 \n筆記・口述: 筆記 \n航海・機関: 航海1級 \n 科 目: 航海 \n問題番号: 大問1 小問1 \n問題内容: ここに問題を記述する。",
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(ContactForm, self).__init__(*args, **kwargs)
        if user and isinstance(user, CustomUser):
            self.fields["name"].initial = user.username
            self.fields["email"].initial = user.email

    def createMIMEText(self):
        user_email = self.cleaned_data["email"]
        subject = self.cleaned_data["subject"]
        message = self.cleaned_data["message"]
        to_email = settings.DEFAULT_FROM_EMAIL

        # MIMETextを作成
        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = user_email
        msg["To"] = to_email

        msg.attach(MIMEText(message, "plain", "utf-8"))

        return msg

    def send_email(self):
        try:
            account = settings.MAILGUN_SMTP_LOGIN
            password = settings.MAILGUN_SMTP_PASSWORD

            host = settings.MAILGUN_SMTP_SERVER
            port = settings.MAILGUN_SMTP_PORT

            # サーバーを指定
            server = SMTP(host, port)
            server.ehlo()
            server.starttls()

            # ログイン処理
            server.login(account, password)

            msg = self.createMIMEText()

            # メール送信
            server.send_message(msg)
        except Exception as e:
            # ここでエラーログを記録
            print(e)
        finally:
            # 閉じる
            if "server" in locals():
                server.quit()

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, TemplateView, UpdateView

from . import forms

# from django.views.decorators.csrf import requires_csrf_token
# from django.http import HttpResponseServerError

User = get_user_model()


# 本番環境でエラーを表示する
# @requires_csrf_token
# def my_customized_server_error(request, template_name='500.html'):
#     import sys
#     from django.views import debug
#     error_html = debug.technical_500_response(request, *sys.exc_info()).content
#     return HttpResponseServerError(error_html)


"""ログインページ"""


class CustomLoginView(LoginView):
    authentication_form = forms.CustomAuthenticationForm
    template_name = "accounts/login.html"


"""サインアップページ"""


class SignupView(FormView):
    form_class = forms.CustomUserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        # ユーザーを保存
        user = form.save(commit=False)
        user.save()

        # 認証
        user = authenticate(
            username=user.email,
            password=form.cleaned_data["password1"],
        )
        return super().form_valid(form)


"""ユーザー情報ページ"""


class ProfileView(TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context


"""ユーザー情報変更ページ"""


class UserChangeView(UpdateView):
    model = User
    form_class = forms.UserChangeForm
    template_name = "accounts/profile_change.html"

    def get_success_url(self):
        user_id = self.object.id
        return reverse("accounts:profile", kwargs={"pk": user_id})

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_message(self, form):
        # save メソッドからインスタンスと変更されたフィールドのリストを取得
        changed_fields = form.change_fields()
        # 変更されたフィールドがあればメッセージを設定
        if changed_fields:
            changed_fields_str = ", ".join(changed_fields)
            messages.success(
                self.request, f"変更された項目: 「 {changed_fields_str} 」"
            )

    def form_valid(self, form):
        form.save()
        self.get_success_message(form)
        return super().form_valid(form)


"""お問合せ画面"""


class ContactFormView(FormView):
    template_name = "accounts/contact.html"
    form_class = forms.ContactForm
    success_url = reverse_lazy("accounts:contact_result")

    def get_form_kwargs(self):
        kwargs = super(ContactFormView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class ContactResultView(TemplateView):
    template_name = "accounts/contact_result.html"

accounts/templates/accounts/contact.html
{% extends "kakomon/base.html" %}
{% load widget_tweaks %}

{% block title %}お問合せ{% endblock %}

{% block base_page %}
<form action="{% url 'accounts:contact' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <h4 class="card-title text-center">お問合せ</h4>
            <table class="profile_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">お名前</th>
                        <td class="data">{% render_field form.name class+="form-control" %}</td>
                    </tr>
                    <tr>
                        <th class="header">メールアドレス</th>
                        <td class="data">{% render_field form.email class+="form-control" %}</td>
                    </tr>
                    <tr>
                        <th class="header">件名</th>
                        <td class="data">{% render_field form.subject class+="form-select" %}</td>
                    </tr>
                    <tr>
                        <th class="header">お問合せ内容</th>
                        <td class="data">{% render_field form.message class+="form-control" %}</td>
                    </tr>
                </tbody>
            </table>
            <div class="d-grid col-3 mx-auto mb-4">
                <button type="submit" class="btn btn-outline-warning">送信</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/contact_result.html
{% extends "kakomon/base.html" %}


{% block title %}お問合せ完了{% endblock %}

{% block base_page %}
<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <h4 class="card-title text-center mb-5">お問合せ完了</h4>
        <p>メールが送信されました。ありがとうございます。</p>
        <a href="{% url 'kakomon:index' %}" class="btn btn-outline-primary mt-5">ホームに戻る</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "kakomon/base.html" %} 

{% block title %}ログイン{% endblock %}

{% block base_page %}
<div class="container">
    <h1 class="title">ログイン</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            {{ field.label }}
            <br>
            <div class="col-7 col-sm-5">{{ field }}</div>
            <br>
            {{ field.error }}
        {% endfor %}
        <br>
        <button class="btn btn-outline-primary mb-3" type="submit">ログイン</button>
        <div><a href="{% url 'accounts:signup' %}" type="submit">アカウント作成</a></div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "kakomon/base.html" %}

{% block title %}ユーザー情報{% endblock %}

{% block base_page %}
<div class="card card-profile my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">プロフィール</h5>
        <table class="profile_table mb-4">
            <tbody>
                <tr>
                    <th class="header">ユーザー名</th>
                    <td class="data">{% if user.username %}{{ user.username }}{% else %}未設定{% endif %}</td>
                </tr>
                <tr>
                    <th class="header">名字</th>
                    <td class="data">{% if user.last_name %}{{ user.last_name }}{% else %}未設定{% endif %}</td>
                </tr>
                <tr>
                    <th class="header">名前</th>
                    <td class="data">{% if user.first_name %}{{ user.first_name }}{% else %}未設定{% endif %}</td>
                </tr>
                <tr>
                    <th class="header">メールアドレス</th>
                    <td class="data">{% if user.email %}{{ user.email }}{% else %}未設定{% endif %}</td>
                </tr>
            </tbody>
        </table>
        <div class="d-grid col-3 mx-auto mb-4">
            <a class="btn btn-outline-warning btn-block" href={% url 'accounts:profile_change' user.id %}>編集する</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile_change.html
{% extends "kakomon/base.html" %}
{% load widget_tweaks %}

{% block title %}ユーザー情報変更{% endblock %}

{% block base_page %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <h5 class="card-title text-center">ユーザー情報変更</h5>
            <table class="profile_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">ユーザー名</th>
                        <td class="data">{% render_field form.username class+="form-control" %}</td>
                    </tr>
                    <tr>
                        <th class="header">名字</th>
                        <td class="data">{% render_field form.last_name class+="form-control" %}</td>
                    </tr>
                    <tr>
                        <th class="header">名前</th>
                        <td class="data">{% render_field form.first_name class+="form-control" %}</td>
                    </tr>
                    <tr>
                        <th class="header">メールアドレス</th>
                        <td class="data">{% render_field form.email class+="form-control" %}</td>
                    </tr>
                </tbody>
            </table>
            <div class="d-grid gap-2 col-6 mx-auto mb-4">
                <button type="submit" class="btn btn-outline-warning">保存</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "kakomon/base.html" %} 

{% block title %}アカウント作成{% endblock %}

{% block base_page %}
<div class="container">
    <h1 class="my-5">アカウント作成</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" name="next" value="regist" type="submit">登録</button>
    </form>
</div>
{% endblock %}